language: en-US
reviews:
  profile: assertive
  high_level_summary: true
  high_level_summary_in_walkthrough: true
  poem: false
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!target/**"
    - "!Cargo.lock"
    - "!Cargo.toml"
chat:
  auto_reply: true
