name: Coverage
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    name: Codecov.io
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      RUST_TEST_THREADS: "1"
    steps:
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Compute Coverage
        run:
          cargo llvm-cov --workspace --ignore-filename-regex tests.rs --codecov --output-path codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: codecov.json
          fail_ci_if_error: true
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: codecov.json
