name: Coverage
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coveralls:
    name: Coveralls
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      RUST_TEST_THREADS: "1"
    steps:
      - name: Install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install llvm-cov
        uses: actions-rs/install@v0.1
        with:
          crate: cargo-llvm-cov
          version: 0.2.3
          use-tool-cache: true
      #- uses: Swatinem/rust-cache@v1
      - name: Coverage
        env:
          RUST_LOG: "debug"
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: --all-features --workspace --lcov --output-path lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.github_token }}
