name: Coveralls
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: coverage-coveralls-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    name: Coveralls.io
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      RUST_TEST_THREADS: "1"
    steps:
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Compute Coverage
        run:
          cargo llvm-cov --workspace --ignore-filename-regex tests.rs --lcov --output-path lcov.info -- --test-threads 1
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: lcov.info
          github-token: ${{ secrets.github_token }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report-lcov
          path: lcov.info
