name: Coverage
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    name: Codecov.io
    continue-on-error: true
    runs-on: ubuntu-latest
    env:
      RUST_TEST_THREADS: "1"
    steps:
      - name: Install rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      #- uses: Swatinem/rust-cache@v1
      - name: Compute Coverage
        run:
          cargo llvm-cov --all-features --workspace --ignore-filename-regex tests.rs --codecov --output-path codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: codecov.json
          fail_ci_if_error: true
